import { library } from '@fortawesome/fontawesome-svg-core'
import { faEnvelope,
     faPhone, faEllipsis,faReply, 
     faUserGroup,faPeopleArrows, faEllipsisVertical,
     faShareFromSquare, faXmark, faPlus,
     faLocationDot,
     faChevronLeft,
     faKey,
     faCode,
     faCheck,
     faCakeCandles,
     faChevronRight,
     faChevronDown,
     faVenusMars,
     faImage,
     faLink,
     faComment,
     faUser,
     faPersonCircleQuestion,
     faUserPlus,
     faPaperPlane,
     faCaretDown,
     faMagnifyingGlass,
     faGear,
     faCamera,
     faLock,
     faChampagneGlasses,
     faDownload,
     faAngleRight,
     faPeopleGroup,
     faSliders,
     faImages
     } from '@fortawesome/free-solid-svg-icons'
import { faSquarePlus,faBell ,faCircleXmark, faFile, faFaceSmile, faEye } from '@fortawesome/free-regular-svg-icons'

library.add({ faLocationDot,faCircleXmark, faCode,faChevronLeft,faLink,faPhone,
     faEnvelope, faSquarePlus, faFile,faEllipsis,
      faReply,faEllipsisVertical,faFaceSmile, 
      faShareFromSquare,faXmark, faPlus,faChampagneGlasses,
       faPeopleArrows,faUserGroup,
       faChevronRight,
       faCamera,
       faImages,
       faChevronDown,
       faDownload,
       faEye,
       faSliders,
       faCaretDown,
       faVenusMars,
       faAngleRight,
       faPeopleGroup,
       faLock,
       faCakeCandles,
       faMagnifyingGlass,
       faUserPlus,
       faPaperPlane,
       faPersonCircleQuestion,
       faCheck,
       faImage,
       faGear,
       faBell,
       faComment,
       faUser,
       faKey })